LilTOJustice/TrueAdaptiveMusic

src/client/kotlin/liltojustice/trueadaptivemusic/client/AdaptiveMusicSoundInstance.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/main/kotlin/liltojustice/trueadaptivemusic/Constants.kt
=> Override in game music and use music slider for volume

build.gradle.kts, src/client/kotlin/liltojustice/trueadaptivemusic/client/FadeInstance.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/main/resources/fabric.mod.json, src/main/resources/trueadaptivemusic.accesswidener
=> Add crossfading support and fix issue when Music volume = 0

src/client/java/liltojustice/trueadaptivemusic/ChangeMusicPackCallback.java, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/TrueAdaptiveMusicClient.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicateException.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicateTree.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/RulesParserException.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/custompredicates/BiomePredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/custompredicates/CombatPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/custompredicates/DimensionPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/custompredicates/StructurePredicate.kt, src/main/kotlin/liltojustice/trueadaptivemusic/Constants.kt, src/main/kotlin/liltojustice/trueadaptivemusic/LogLevel.kt, src/main/kotlin/liltojustice/trueadaptivemusic/Logger.kt, src/main/kotlin/liltojustice/trueadaptivemusic/TrueAdaptiveMusic.kt
=> Add exception types, handling and logging

src/client/kotlin/liltojustice/trueadaptivemusic/client/AdaptiveMusicSoundInstance.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/FadeInstance.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicLoadException.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/PlayableSound.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/PlayableSoundEvent.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/PlayableSoundFile.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/TrueAdaptiveMusicClient.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicateException.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicateTree.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/RulesParserException.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/custompredicates/BiomePredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/custompredicates/CombatPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/custompredicates/DimensionPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/custompredicates/RootPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/custompredicates/StructurePredicate.kt, src/main/kotlin/liltojustice/trueadaptivemusic/TrueAdaptiveMusic.kt
Add support for individual music files as well as using an array for musicPath to specify multiple sources to be chosen at random.
closes #19
=> Improve music path system

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/TrueAdaptiveMusicClient.kt
=> Fix first time startup and vanilla sounds with no pack.

src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/CombatPredicate.kt
=> Refine combat predicate logic

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/BossPredicate.kt, src/main/resources/trueadaptivemusic.accesswidener
=> Boss Predicate

src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/DayTimePredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/NightTimePredicate.kt
=> Add Day & Night predicates.

src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicateTree.kt
=> Predicate Node Moving

src/client/java/liltojustice/trueadaptivemusic/client/ChangeMusicPackCallback.java, src/client/kotlin/liltojustice/trueadaptivemusic/client/Callbacks.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicPack.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/TrueAdaptiveMusicClient.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/screen/EditPackScreen.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/screen/MainScreen.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PackListWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicateTree.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/sound/ZipSoundFile.kt, src/main/kotlin/liltojustice/trueadaptivemusic/ZipInputStream.kt
=> Music Pack Selection

src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt
=> Add music event support in UI

src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/ContainerWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/DropdownWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/MultiSelectDropdownWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt
I hate building UI backend
closes #54
=> Kinda fix the scrolling

src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/screen/EditPackScreen.kt
=> Add close button in edit pack screen

src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/screen/MainScreen.kt
=> Add refresh button to pack list screen

.github/workflows/main.yml, CHANGELOG.md
=> Add publishing workflows

.github/workflows/validate.yml
Reverts LilTOJustice/TrueAdaptiveMusic#98
=> Revert "Update validate.yml"

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/DropdownWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/MultiSelectDropdownWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/PredicateParam.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/BiomePredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/BossPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/DimensionPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/StructurePredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/StructureSetPredicate.kt
Support multiple IDs for predicates that take an ID
closes #28
=> ID Lists for Predicates

src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/CheckboxWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/TextInputWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/HeightPredicate.kt
=> Add HeightPredicate

src/client/kotlin/liltojustice/trueadaptivemusic/client/enum/Weather.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/WeatherPredicate.kt
=> Add weather predicate and enum handling

src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/FirstDayPredicate.kt
=> Add FirstDayPredicate

src/client/java/liltojustice/trueadaptivemusic/client/PlaySoundNowCallback.java, src/client/kotlin/liltojustice/trueadaptivemusic/client/Callbacks.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/TrueAdaptiveMusicClient.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/screen/EditPackScreen.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/screen/MainScreen.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/ClickableTextWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/ContainerWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/DropdownWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/MultiSelectDropdownWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt
=> Music Previews in Edit Screen

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/CombatPredicate.kt
=> Fix combat logic

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt
=> Fix source leaks causing source count to hit 8

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicPack.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicateTree.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/HeightPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/MusicPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/WeatherPredicate.kt
=> Music Delays

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt
=> Resume music after switching between two predicate nodes

src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicateTree.kt
=> Rework Predicate Choice Logic

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicPack.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/enums/Weather.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/ffmpeg/FFMpeg.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/ffmpeg/FFMpegAudioStream.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PackListWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/instance/AdaptiveMusicSoundInstance.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/types/WeatherPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/sound/PlayableSoundEvent.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/sound/PlayableSoundFile.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/sound/RegularSoundFile.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/sound/SoundFile.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/sound/ZipSoundFile.kt
closes #123 
closes #117 
Add a whole lot more than mp3 and wav support, supports practically any audio file now.
=> Support more audio file types

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/TextInputWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/predicate/MusicPredicateTree.kt
=> Add support for track delay noise

src/client/kotlin/liltojustice/trueadaptivemusic/client/MusicManager.kt
=> Allow predicate switching during event music playback

build.gradle.kts, gradle.properties, src/client/kotlin/liltojustice/trueadaptivemusic/client/integration/TrueAdaptiveMusicModMenu.kt, src/main/resources/fabric.mod.json
=> Modmenu integration

src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/screen/EditPackScreen.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/ClickableTextWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/ContainerWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/DataWrapped.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PackStructureWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateTreeWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PredicateViewWidget.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/MusicPredicateTree.kt
=> Improve predicate node moving in Pack Structure view

src/client/kotlin/liltojustice/trueadaptivemusic/client/music/MusicManager.kt
=> Fade out music when a jukebox is playing nearby

.github/workflows/publish.yml, .github/workflows/push_update.yml
Rework publish workflow and create workflow for pushing new updates as patches to all minecraft version branches
=> Rework process for updating and publishing

src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/GameModePredicate.kt
=> Added GameModePredicate.kt

src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/MoonPhasePredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/WeatherPredicate.kt
=> Add MoonPhasePredicate.kt

src/client/kotlin/liltojustice/trueadaptivemusic/client/identifier/EntityTypeIdentifier.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/BossPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/RidingPredicate.kt
=> Add RidingPredicate

src/client/kotlin/liltojustice/trueadaptivemusic/client/identifier/StatusEffectIdentifier.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/BossPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/RidingPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/StatusEffectPredicate.kt
=> StatusEffect Predicate

src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/PillagerRaidPredicate.kt
=> Pillager Raid Predicate

src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/CombatPredicate.kt
=> Only play combat music if the player is aware of the enemy

src/client/kotlin/liltojustice/trueadaptivemusic/client/gui/widget/PackStructureWidget.kt
=> Add red arrow for invalid predicate moving

src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/MusicPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/MusicPredicateTree.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/CombatPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/DayTimePredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/NightTimePredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/RootPredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/StructurePredicate.kt, src/client/kotlin/liltojustice/trueadaptivemusic/client/trigger/predicate/types/StructureSetPredicate.kt
=> Predicate Optimization

src/client/java/liltojustice/trueadaptivemusic/client/mixin/SoundManagerPauseAllMixin.java, src/client/kotlin/liltojustice/trueadaptivemusic/client/music/MusicManager.kt
=> Fade on pause

trueadaptivemusicdocs/docs/Advanced Topics/Modded Predicates and Events.md, trueadaptivemusicdocs/docs/Music Packs/Events.md, trueadaptivemusicdocs/docs/Music Packs/Predicates.md
See title :)
Infinity Castle was goated fr
=> Update docs for 1.3
